import type { Theme } from "skybridge/web";

const lightStyleVariables: Record<string, string> = {
  "--color-background-primary": "#fff",
  "--color-background-secondary": "#f9f9f9",
  "--color-background-tertiary": "#f3f3f3",
  "--color-background-inverse": "#181818",
  "--color-background-ghost": "color-mix(in oklab,#0d0d0d 0.0%,transparent)",
  "--color-background-disabled": "color-mix(in oklab,#0d0d0d 5.0%,transparent)",
  "--color-text-primary": "#0d0d0d",
  "--color-text-secondary": "#5d5d5d",
  "--color-text-tertiary": "#8f8f8f",
  "--color-text-inverse": "#fff",
  "--color-text-ghost": "#0d0d0d",
  "--color-text-info": "#3a83f7",
  "--color-text-danger": "#fa423e",
  "--color-text-success": "#2c6732",
  "--color-text-warning": "#87401d",
  "--color-text-disabled": "#8f8f8f",
  "--color-border-primary": "color-mix(in oklab,#0d0d0d 10.0%,transparent)",
  "--color-border-secondary": "color-mix(in oklab,#0d0d0d 5.0%,transparent)",
  "--color-border-tertiary": "color-mix(in oklab,#0d0d0d 15%,transparent)",
  "--color-border-inverse": "#fff",
  "--color-border-ghost": "color-mix(in oklab,#0d0d0d 0.0%,transparent)",
  "--color-border-disabled": "color-mix(in oklab,#0d0d0d 6.0%,transparent)",
  "--color-ring-primary": "#2c67c5",
  "--color-ring-secondary": "#2c67c5",
  "--color-ring-inverse": "#2c67c5",
  "--color-ring-info": "#2c67c5",
  "--color-ring-danger": "#ff8583",
  "--color-ring-success": "#2c67c5",
  "--color-ring-warning": "#2c67c5",
  "--font-sans":
    '"ui-sans-serif", "-apple-system", "system-ui", "Segoe UI", "Helvetica", "Apple Color Emoji", "Arial", "sans-serif", "Segoe UI Emoji", "Segoe UI Symbol"',
  "--font-mono":
    '"ui-monospace", "SFMono-Regular", "SF Mono", "Menlo", "Consolas", "Liberation Mono", "monospace"',
  "--font-weight-normal": "400",
  "--font-weight-medium": "500",
  "--font-weight-semibold": "600",
  "--font-weight-bold": "700",
  "--font-text-xs-size": ".75rem",
  "--font-text-sm-size": ".875rem",
  "--font-text-md-size": "1rem",
  "--font-text-lg-size": "1.125rem",
  "--font-heading-xs-size": "1rem",
  "--font-heading-sm-size": "1.125rem",
  "--font-heading-md-size": "1.25rem",
  "--font-heading-lg-size": "1.5rem",
  "--font-heading-xl-size": "2rem",
  "--font-heading-2xl-size": "2.25rem",
  "--font-heading-3xl-size": "3rem",
  "--font-text-xs-line-height": "1.125rem",
  "--font-text-sm-line-height": "1.25rem",
  "--font-text-md-line-height": "1.5rem",
  "--font-text-lg-line-height": "1.8125rem",
  "--font-heading-xs-line-height": "1.5rem",
  "--font-heading-sm-line-height": "1.625rem",
  "--font-heading-md-line-height": "1.625rem",
  "--font-heading-lg-line-height": "1.75rem",
  "--font-heading-xl-line-height": "2.375rem",
  "--font-heading-2xl-line-height": "2.625rem",
  "--font-heading-3xl-line-height": "3rem",
  "--border-radius-xs": ".25rem",
  "--border-radius-sm": ".375rem",
  "--border-radius-md": ".5rem",
  "--border-radius-lg": ".625rem",
  "--border-radius-xl": ".75rem",
  "--border-radius-full": "9999px",
  "--border-width-regular": ".5px",
  "--shadow-hairline": "0 0 0 .5px #0000001a",
  "--shadow-sm": "0 1px 2px -1px rgb(0 0 0 / .08)",
  "--shadow-md": "0 2px 4px -1px rgb(0 0 0 / .08)",
  "--shadow-lg": "0 4px 8px -2px rgb(0 0 0 / .1)",
};

const darkColorOverrides: Record<string, string> = {
  "--color-background-primary": "#212121",
  "--color-background-secondary": "#303030",
  "--color-background-tertiary": "#414141",
  "--color-background-inverse": "#f3f3f3",
  "--color-background-ghost": "color-mix(in oklab,#fff 0.0%,transparent)",
  "--color-background-disabled": "color-mix(in oklab,#fff 5.0%,transparent)",
  "--color-text-primary": "#fff",
  "--color-text-secondary": "#cdcdcd",
  "--color-text-tertiary": "#afafaf",
  "--color-text-inverse": "#0d0d0d",
  "--color-text-ghost": "#fff",
  "--color-border-primary": "color-mix(in oklab,#fff 10.0%,transparent)",
  "--color-border-secondary": "color-mix(in oklab,#fff 5.0%,transparent)",
  "--color-border-tertiary": "color-mix(in oklab,#fff 15%,transparent)",
  "--color-border-inverse": "#181818",
  "--color-border-ghost": "color-mix(in oklab,#fff 0.0%,transparent)",
  "--color-border-disabled": "color-mix(in oklab,#fff 6.0%,transparent)",
};

export function chatgptStyleVariables(theme: Theme): Record<string, string> {
  return theme === "dark"
    ? { ...lightStyleVariables, ...darkColorOverrides }
    : lightStyleVariables;
}

export function chatgptHostContextExtras(theme: Theme) {
  return {
    styles: { variables: chatgptStyleVariables(theme) },
    containerDimensions: { maxWidth: 768 },
    availableDisplayModes: ["inline", "fullscreen", "pip"],
    userAgent: "chatgpt",
    timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  };
}
